apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-flagd
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-flagd
        app.kubernetes.io/component: flagd
    spec:
      serviceAccountName: opentelemetry-demo
      initContainers:
        - name: init-config
          image: busybox
          command:
            - sh
            - -c
            - cp /config-ro/demo.flagd.json /config-rw/demo.flagd.json && cat /config-rw/demo.flagd.json
          volumeMounts:
            - mountPath: /config-ro
              name: config-ro
            - mountPath: /config-rw
              name: config-rw
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.11.1
          imagePullPolicy: IfNotPresent
          command:
            - /flagd-build
            - start
            - --uri
            - file:./etc/flagd/demo.flagd.json
          ports:
            - containerPort: 8013
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: opentelemetry-demo-otelcol
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: FLAGD_METRICS_EXPORTER
              value: otel
            - name: FLAGD_OTEL_COLLECTOR_URI
              value: $(OTEL_COLLECTOR_NAME):4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
          resources:
            limits:
              memory: 75Mi
          volumeMounts:
            - name: config-rw
              mountPath: /etc/flagd
        - name: flagdui
          image: ghcr.io/open-telemetry/demo:1.12.0-flagdui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: opentelemetry-demo-otelcol
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: FLAGD_METRICS_EXPORTER
              value: otel
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4318
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
          resources:
            limits:
              memory: 75Mi
          volumeMounts:
            - mountPath: /app/data
              name: config-rw
      volumes:
        - name: config-rw
          emptyDir: {}
        - name: config-ro
          configMap:
            name: opentelemetry-demo-flagd-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-flagd
spec:
  type: ClusterIP
  ports:
    - port: 8013
      name: tcp-service
      targetPort: 8013
    - port: 4000
      name: tcp-service-0
      targetPort: 4000
  selector:
    opentelemetry.io/name: opentelemetry-demo-flagd