apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-frauddetectionservice
  labels:
    app.kubernetes.io/component: frauddetectionservice
    app.kubernetes.io/name: opentelemetry-demo-frauddetectionservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-frauddetectionservice
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-frauddetectionservice
        app.kubernetes.io/component: frauddetectionservice
    spec:
      serviceAccountName: opentelemetry-demo
      initContainers:
        - name: wait-for-kafka
          image: busybox:latest
          command:
            - sh
            - -c
            - "until nc -z -v -w30 opentelemetry-demo-kafka 9092; do echo waiting for kafka; sleep 2; done;"
      containers:
        - name: frauddetectionservice
          image: ghcr.io/open-telemetry/demo:1.12.0-frauddetectionservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8013
              name: flagd
          resources:
            limits:
              memory: 300Mi
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: opentelemetry-demo-otelcol
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: KAFKA_SERVICE_ADDR
              value: opentelemetry-demo-kafka:9092
            - name: FLAGD_HOST
              value: opentelemetry-demo-flagd
            - name: FLAGD_PORT
              value: "8013"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4318
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0